### ISSUE TITLE
The recent commit 'XcodeProject.load' is exception

### ISSUE THREAD

**Issue by shanghaiMichael** [kronenthaler/mod-pbxproj#136]
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    project = XcodeProject.load('test_mod.xcodeproj/project.pbxproj')
  File "build/bdist.macosx-10.12-intel/egg/pbxproj/XcodeProject.py", line 64, in load
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 31, in ParseFromFile
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 35, in ParseFromString
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 44, in _parse
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 56, in _parse_dictionary
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 86, in _parse_dictionary_entry
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 158, in _parse_value
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 56, in _parse_dictionary
  File "build/bdist.macosx-10.12-intel/egg/openstep_parser/openstep_parser.py", line 83, in _parse_dictionary_entry
Exception: Expected = after a key. Found B @ 160

**Comment by kronenthaler** [comment]
Can you attach the project you are using? It seems related to something else.

**Comment by shanghaiMichael** [comment]
Sorry , I'm wrong
