### ISSUE TITLE
 class PBXKey(unicode): NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by rublevma** [kronenthaler/mod-pbxproj#158]
> Traceback (most recent call last):
  File "E:/Python/xcode/xcode_custom.py", line 4, in <module>
    from pbxproj import XcodeProject
  File "C:\Python35\lib\site-packages\pbxproj\__init__.py", line 24, in <module>
    from pbxproj.PBXGenericObject import PBXGenericObject
  File "C:\Python35\lib\site-packages\pbxproj\PBXGenericObject.py", line 5, in <module>
    from pbxproj.PBXKey import PBXKey
  File "C:\Python35\lib\site-packages\pbxproj\PBXKey.py", line 1, in <module>
    class PBXKey(unicode):
NameError: name 'unicode' is not defined

This error appear when i try use it with Python 3.5.1

**Comment by kronenthaler** [comment]
Thanks for the report. However python 3 is not supported yet. Closing this ticket as duplicated of #101
