### ISSUE TITLE
UnicodeEncodeError when trying to save a newly created Cocoa Touch Framework project

### ISSUE THREAD

**Issue by Slangen** [kronenthaler/mod-pbxproj#183]
Step 1: Create a new Objective-C Cocoa Touch Framework project, including unit tests.
Step 2: `project = XcodeProject.load('test.xcodeproj/project.pbxproj')`
Step 3: `project.save()`

Result:
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/Library/Python/2.7/site-packages/pbxproj/XcodeProject.py", line 30, in save
    f.write(self.__repr__())
    File "/Library/Python/2.7/site-packages/pbxproj/XcodeProject.py", line 40, in __repr__
    return u'// !$*UTF8*$!\n' + super(XcodeProject, self).__repr__()
    File "/Library/Python/2.7/site-packages/pbxproj/PBXGenericObject.py", line 80, in __repr__
    return self._print_object()
    File "/Library/Python/2.7/site-packages/pbxproj/PBXGenericObject.py", line 88, in _print_object
    indentation_increment)
    File "/Library/Python/2.7/site-packages/pbxproj/PBXGenericObject.py", line 112, in _format
    indentation_increment)
    File "/Library/Python/2.7/site-packages/pbxproj/PBXObjects.py", line 40, in _print_object
    indentation_increment)
    File "/Library/Python/2.7/site-packages/pbxproj/PBXGenericObject.py", line 88, in _print_object
    indentation_increment)
    File "/Library/Python/2.7/site-packages/pbxproj/PBXGenericObject.py", line 112, in _format
    indentation_increment)
    File "/Library/Python/2.7/site-packages/pbxproj/PBXGenericObject.py", line 88, in _print_object
    indentation_increment)
    File "/Library/Python/2.7/site-packages/pbxproj/PBXGenericObject.py", line 121, in _format
    value = PBXGenericObject._escape(value.__str__())
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 8: ordinal not in range(128)

**Comment by Slangen** [comment]
I was actually trying to replicate another issue I'm having where 

    project.add_folder(...)

doesn't add the .h files to the Headers build phase in a Cocoa Touch Framework project.

**Comment by kronenthaler** [comment]
A fix was released yesterday for the unicode problem (2.2.1) and try again.
For the headers problem, be sure to check the [wiki](https://github.com/kronenthaler/mod-pbxproj/wiki/Groups-and-Folders)
