### ISSUE TITLE
KeyError: u'\t' when loading existing Xcode project

### ISSUE THREAD

**Issue by avdhut1990** [kronenthaler/mod-pbxproj#206]
Getting the following error when loading an existing Xcode project:

> Traceback (most recent call last):
  File "./xcode_mod.sh", line 17, in <module>
    project = XcodeProject.load(xcode_project)
  File "build/bdist.macosx-10.13-intel/egg/pbxproj/XcodeProject.py", line 64, in load
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 43, in ParseFromFile
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 47, in ParseFromString
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 56, in _parse
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 68, in _parse_dictionary
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 98, in _parse_dictionary_entry
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 170, in _parse_value
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 68, in _parse_dictionary
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 98, in _parse_dictionary_entry
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 170, in _parse_value
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 68, in _parse_dictionary
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 98, in _parse_dictionary_entry
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 174, in _parse_value
  File "build/bdist.macosx-10.13-intel/egg/openstep_parser/openstep_parser.py", line 148, in _parse_literal
KeyError: u'\t'

Attaching sh file as well as Xcode project for your reference.

[Support Files.zip](https://github.com/kronenthaler/mod-pbxproj/files/2029660/Support.Files.zip)

**Comment by kronenthaler** [comment]
Thanks for your report. It seems it's a duplicated of #200.

**Comment by avdhut1990** [comment]
Upon referring issue #200 and the suspected root cause I found that before modifying the Xcode project using pbxproj, the pbxproj file included the actual tab space character \t
After modification, the \t is replaced by an actual tab space post which the given error is generated.
