### ISSUE TITLE
openstep_parser.py has bug

### ISSUE THREAD

**Issue by PiPiPrawn** [kronenthaler/mod-pbxproj#213]
When I loaded project.pbxproj through load, the following error occurred and the script seemed to have a problem.

Traceback (most recent call last):
  File "ipa.py", line 16, in <module>
    project = XcodeProject.load('Test.xcodeproj/project.pbxproj')
  File "build/bdist.macosx-10.13-x86_64/egg/pbxproj/XcodeProject.py", line 64, in load
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 43, in ParseFromFile
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 47, in ParseFromString
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 56, in _parse
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 68, in _parse_dictionary
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 98, in _parse_dictionary_entry
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 170, in _parse_value
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 68, in _parse_dictionary
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 98, in _parse_dictionary_entry
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 170, in _parse_value
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 68, in _parse_dictionary
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 98, in _parse_dictionary_entry
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 170, in _parse_value
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 68, in _parse_dictionary
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 98, in _parse_dictionary_entry
  File "build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py", line 169, in _parse_value
IndexError: string index out of range

**Comment by PiPiPrawn** [comment]
git clone mod-pbxproj
cd mod-pbxproj
sudo python setup.py install
During the installation, I found that the contents of the bdist.macosx-10.13-x86_64 directory had been removed and installed in the python.2.7 site-packages directory

**Comment by PiPiPrawn** [comment]
The contents of the directory bdist.macosx-10.13-x86_64 have been removed. Why does the error message show build/bdist.macosx-10.13-x86_64/egg/openstep_parser/openstep_parser.py
