### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by xiaoheiai4719** [kronenthaler/mod-pbxproj#214]
Traceback (most recent call last):
  File "testProject.py", line 24, in <module>
    project.save()
  File "/Users/dong/miniconda2/lib/python2.7/site-packages/pbxproj/XcodeProject.py", line 30, in save
    f.write(self.__repr__())
  File "/Users/dong/miniconda2/lib/python2.7/site-packages/pbxproj/XcodeProject.py", line 40, in __repr__
    return u'// !$*UTF8*$!\n' + super(XcodeProject, self).__repr__()
  File "/Users/dong/miniconda2/lib/python2.7/site-packages/pbxproj/PBXGenericObject.py", line 80, in __repr__
    return self._print_object()
  File "/Users/dong/miniconda2/lib/python2.7/site-packages/pbxproj/PBXGenericObject.py", line 88, in _print_object
    indentation_increment)
  File "/Users/dong/miniconda2/lib/python2.7/site-packages/pbxproj/PBXGenericObject.py", line 112, in _format
    indentation_increment)
  File "/Users/dong/miniconda2/lib/python2.7/site-packages/pbxproj/PBXObjects.py", line 40, in _print_object
    indentation_increment)
  File "/Users/dong/miniconda2/lib/python2.7/site-packages/pbxproj/PBXGenericObject.py", line 88, in _print_object
    indentation_increment)
  File "/Users/dong/miniconda2/lib/python2.7/site-packages/pbxproj/PBXGenericObject.py", line 112, in _format
    indentation_increment)
  File "/Users/dong/miniconda2/lib/python2.7/site-packages/pbxproj/PBXGenericObject.py", line 88, in _print_object
    indentation_increment)
  File "/Users/dong/miniconda2/lib/python2.7/site-packages/pbxproj/PBXGenericObject.py", line 121, in _format
    value = PBXGenericObject._escape(value.__str__(), exclude=[u"\'"])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

i meet this when i try to save my project.

**Comment by kronenthaler** [comment]
There is not enough information to continue investigating this ticket.

**Comment by haolly** [comment]
I just encounter the same issus

**Comment by kronenthaler** [comment]
@haolly @xiaoheiai4719 Please provide a redacted project.pbxproj otherwise this issue cannot be debugged.

**Comment by haolly** [comment]
@kronenthaler I have fixed the problem  following this blog https://markhneedham.com/blog/2015/05/21/python-unicodeencodeerror-ascii-codec-cant-encode-character-uxfc-in-position-11-ordinal-not-in-range128/
