### ISSUE TITLE
AttributeError: 'unicode' object has no attribute '_get_comment' [BUG]

### ISSUE THREAD

**Issue by kamendo** [kronenthaler/mod-pbxproj#264]
**Describe the bug**
I installed mod-pbxproj and created a simple perl script

from pbxproj import XcodeProject
project = XcodeProject.load('ActivationEngineIOS.xcodeproj/project.pbxproj')
project.add_file('MyClass.swift', force=False)
project.save()

I got the following error:
Traceback (most recent call last):
  File "prepare-project.py", line 9, in <module>
    project.save()
  File "/Library/Python/2.7/site-packages/pbxproj/XcodeProject.py", line 35, in save
    f.write(self.__repr__() + "\n")
  File "/Library/Python/2.7/site-packages/pbxproj/XcodeProject.py", line 47, in __repr__
    return '// !$*UTF8*$!\n' + super(XcodeProject, self).__repr__()
  File "/Library/Python/2.7/site-packages/pbxproj/PBXGenericObject.py", line 75, in __repr__
    return self._print_object()
  File "/Library/Python/2.7/site-packages/pbxproj/PBXGenericObject.py", line 83, in _print_object
    indentation_increment)
  File "/Library/Python/2.7/site-packages/pbxproj/PBXGenericObject.py", line 107, in _format
    indentation_increment)
  File "/Library/Python/2.7/site-packages/pbxproj/PBXObjects.py", line 42, in _print_object
    result += indentation_depth + '\t{0} = {1};\n'.format(value.get_id().__repr__(), obj)
  File "/Library/Python/2.7/site-packages/pbxproj/PBXKey.py", line 8, in __repr__
    comment = self._get_comment()
  File "/Library/Python/2.7/site-packages/pbxproj/PBXKey.py", line 20, in _get_comment
    return self.get_parent()._resolve_comment(self)
  File "/Library/Python/2.7/site-packages/pbxproj/PBXGenericObject.py", line 154, in _resolve_comment
    return self[key]._get_comment()
  File "/Library/Python/2.7/site-packages/pbxproj/pbxsections/PBXBuildFile.py", line 41, in _get_comment
    comment = self.fileRef._get_comment()
AttributeError: 'unicode' object has no attribute '_get_comment'

**System information** 
1. pbxproj version used: 2.9.0
2. python version used: 2.7
3. Xcode version used:11.2.1

As a side effect my project can't be opened by Xcode any more

**Comment by kronenthaler** [comment]
Thanks for your report. This is a known issue of python 2.7, which is automatically resolved in python3. My recommendation is to upgrade to python3 as python 2.7 reached end of life Jan-2020.

**Comment by kamendo** [comment]
Thank you! Yet, I think you should change the library to produce a warning, instead of deleting my project file 🥇

**Comment by kronenthaler** [comment]
As recommeded in the documentation [here](https://github.com/kronenthaler/mod-pbxproj/wiki/Load-and-save#create-a-backup), it's a good idea to create a backup before calling the `save` method. 
If you are using the CLI all commands support a `--backup` flag as well.

**Comment by noway** [comment]
What's the last working version without that error?

**Comment by kronenthaler** [comment]
Last working version for python 2.7 is 2.7.0 or 2.8.0. Note that these versions as python 2.7 are unsupported.
