### ISSUE TITLE
[BUG] can't add a .modulemap file

### ISSUE THREAD

**Issue by sunsetroads** [kronenthaler/mod-pbxproj#274]
**Can't add a .modulemap file**
When add file or folder that has a .modulemap, it will crash.  If  remove the .modulemap file, it will ok
I had add the file type in ProjectFiles.py ` u'.modulemap': (u'sourcecode.module-map', u'PBXFileReference')
`
**System information** 
1. pbxproj version used: 2.5.1
2. python version used: 3.7
3. Xcode version used:  11.3.1

**Test Code**
```
from pbxproj import XcodeProject
p = XcodeProject.load('../hantai/Unity-iPhone.xcodeproj/project.pbxproj')
p.add_folder('./firebase')
# p.add_file('./firebase/module.modulemap')
p.save()
```
**Error Log**
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    p.add_folder('./firebase')
  File "/usr/local/lib/python3.7/site-packages/pbxproj/pbxextensions/ProjectFiles.py", line 384, in add_folder
    file_options=file_options)
  File "/usr/local/lib/python3.7/site-packages/pbxproj/pbxextensions/ProjectFiles.py", line 151, in add_file
    results.extend(self._create_build_files(file_ref, target_name, expected_build_phase, file_options))
  File "/usr/local/lib/python3.7/site-packages/pbxproj/pbxextensions/ProjectFiles.py", line 424, in _create_build_files
    build_phases = target.get_or_create_build_phase(expected_build_phase)
  File "/usr/local/lib/python3.7/site-packages/pbxproj/pbxsections/PBXGenericTarget.py", line 23, in get_or_create_build_phase
    build_phase = self._get_class_reference(build_phase_type).create(*create_parameters)
TypeError: create() missing 1 required positional argument: 'path'
```

**Comment by kronenthaler** [comment]
Thanks for your report.
Normally .modulemap files are part of a framework file, and they shouldn't be added to you project directly. 

To add a framework follow the ![wiki page](https://github.com/kronenthaler/mod-pbxproj/wiki/files#add-a-libraryframework)
