### ISSUE TITLE
[BUG]ERROR: Failed building wheel for pbxproj

### ISSUE THREAD

**Issue by niyaoyao** [kronenthaler/mod-pbxproj#297]
**Describe the bug**
MacOS Version: Big Sur, 11.0.1 (20B29)
When I run ```pip install pbxproj``` command line in terminal, it will report error as below.

```
  ERROR: Command errored out with exit status 1:
   command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ly/z_gkzgq50dd8ps2hjl7q1_ww0000gn/T/pip-wheel-eQXkBh/pbxproj/setup.py'"'"'; __file__='"'"'/private/var/folders/ly/z_gkzgq50dd8ps2hjl7q1_ww0000gn/T/pip-wheel-eQXkBh/pbxproj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/ly/z_gkzgq50dd8ps2hjl7q1_ww0000gn/T/pip-wheel-qEsIGt
       cwd: /private/var/folders/ly/z_gkzgq50dd8ps2hjl7q1_ww0000gn/T/pip-wheel-eQXkBh/pbxproj/
  Complete output (28 lines):
  DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/ly/z_gkzgq50dd8ps2hjl7q1_ww0000gn/T/pip-wheel-eQXkBh/pbxproj/setup.py", line 78, in <module>
      cmdclass={'test': NoseTestCommand, 'coverage': NoseTestCoverage})
    File "/Users/qjj/Library/Python/2.7/lib/python/site-packages/setuptools/__init__.py", line 161, in setup
      _install_setup_requires(attrs)
    File "/Users/qjj/Library/Python/2.7/lib/python/site-packages/setuptools/__init__.py", line 156, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/Users/qjj/Library/Python/2.7/lib/python/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
      replace_conflicting=True,
    File "/Users/qjj/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 782, in resolve
      replace_conflicting=replace_conflicting
    File "/Users/qjj/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 1065, in best_match
      return self.obtain(req, installer)
    File "/Users/qjj/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 1077, in obtain
      return installer(requirement)
    File "/Users/qjj/Library/Python/2.7/lib/python/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/Users/qjj/Library/Python/2.7/lib/python/site-packages/setuptools/installer.py", line 133, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "/Users/qjj/Library/Python/2.7/lib/python/site-packages/setuptools/wheel.py", line 102, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "/Users/qjj/Library/Python/2.7/lib/python/site-packages/setuptools/wheel.py", line 110, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "/Users/qjj/Library/Python/2.7/lib/python/site-packages/setuptools/wheel.py", line 131, in _convert_metadata
      os.mkdir(destination_eggdir)
  OSError: [Errno 17] File exists: '/private/var/folders/ly/z_gkzgq50dd8ps2hjl7q1_ww0000gn/T/pip-wheel-eQXkBh/pbxproj/.eggs/coverage-5.3.1-py2.7-macosx-11.0-x86_64.egg'
  ----------------------------------------
  ERROR: Failed building wheel for pbxproj
```

**System information** 
1. pbxproj version used: latest, not specify.
2. python version used:  2.7
3. Xcode version used: 12.3

**Comment by niyaoyao** [comment]
Hi, guys, I find out the solution. It seems that, the pbxproj module is depend on coverage module and the **coverage-5.3.1-cp27-cp27m-macosx_10_9_x86_64.wh**l have something wrong. 

We should run ```pip install coverage``` before install pbxproj.
