### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by jonnyijapan** [kronenthaler/mod-pbxproj#31]
Using Python 2.7.6.

Error is: NameError: name 'PBXSourcesBuildPhase' is not defined
```
Traceback (most recent call last):
  File "zzz.py", line 3, in <module>
    from mod_pbxproj import XcodeProject
  File "/Users/xx/Dropbox/vv/scripts/yy/mod_pbxproj.py", line 148, in <module>
    class PBXFileReference(PBXType):
  File "/Users/xx/Dropbox/vv/scripts/yy/mod_pbxproj.py", line 162, in PBXFileReference
    '.swift': ('sourcecode.swift', PBXSourcesBuildPhase),
```

**Comment by kronenthaler** [comment]
Fixed, please download the file again.

**Comment by jonnyijapan** [comment]
Thanks. I could now import it... also opening my project.pbxproj works... so here I go...

**Comment by jonnyijapan** [comment]
Just want to update here and say that I got everything to work. Still works in Xcode 6.2. Great project.
