### ISSUE TITLE
Does not support UTF-8 encoding

### ISSUE THREAD

**Issue by luowenxing** [kronenthaler/mod-pbxproj#93]
I use python2.7 in OSX and my projectPath include Chinese so I add `# coding=utf-8` to my script.Then script run failed with error described
```
Traceback (most recent call last):
  File "mergePbxproj.py", line 8, in <module>
    project.save()
  File "/Library/Python/2.7/site-packages/mod_pbxproj-1.3.1-py2.7.egg/mod_pbxproj/mod_pbxproj.py", line 1265, in save
    self.save_new_format(file_name, sort)
  File "/Library/Python/2.7/site-packages/mod_pbxproj-1.3.1-py2.7.egg/mod_pbxproj/mod_pbxproj.py", line 1327, in save_new_format
    self._printNewXCodeFormat(out, self.data, '', enters=True, sort=sort)
  File "/Library/Python/2.7/site-packages/mod_pbxproj-1.3.1-py2.7.egg/mod_pbxproj/mod_pbxproj.py", line 1420, in _printNewXCodeFormat
    self._printNewXCodeFormat(out, value, '\t\t' + deep, enters=section[1])
  File "/Library/Python/2.7/site-packages/mod_pbxproj-1.3.1-py2.7.egg/mod_pbxproj/mod_pbxproj.py", line 1427, in _printNewXCodeFormat
    self._printNewXCodeFormat(out, root[key], '\t' + deep, enters=enters)
  File "/Library/Python/2.7/site-packages/mod_pbxproj-1.3.1-py2.7.egg/mod_pbxproj/mod_pbxproj.py", line 1468, in _printNewXCodeFormat
    out.write('"' + XcodeProject.addslashes(root.encode("utf-8")) + '"')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 14: ordinal not in range(128)
```
I am new to python and I hope you could help me with the issue,thx!

**Comment by kronenthaler** [comment]
Thanks for your feedback, although this question is not related to the project. Being a generic python error there are solutions on stackoverflow for it: http://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by luowenxing** [comment]
I tried the solution of stackoverflow but got this now.
```
/Library/Python/2.7/site-packages/mod_pbxproj-1.3.1-py2.7.egg/mod_pbxproj/mod_pbxproj.py:743: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  and g.get_name() == name]
Traceback (most recent call last):
  File "mergePbxproj.py", line 12, in <module>
    project.add_folder(folderPath)
  File "/Library/Python/2.7/site-packages/mod_pbxproj-1.3.1-py2.7.egg/mod_pbxproj/mod_pbxproj.py", line 920, in add_folder
    self.objects[r.id] = r
AttributeError: 'NoneType' object has no attribute 'id'
```
I have succeed in NonChinese folder but still failed in folder contains Chinese.Could you give me some help pls?

**Comment by kronenthaler** [comment]
Not an issue related to the project.
